spring:
  application:
    name: classification
  config:
    import: optional:configserver:http://config-service:8080/
    activate:
      on-profile: prod
  cloud:
    config:
      profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: et_classification
eureka:
  client:
    serviceUrl:
      defaultZone: http://naming-server:8080/eureka/

server:
  port: 8080   # inside container, docker-compose maps it to 9001
