spring:
  application:
    name: classification
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: dev
  cloud:
    config:
      profile: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:6000/postgres}
    username: ${DB_USERNAME:test}
    password: ${DB_PASSWORD:test}
  liquibase:
    default-schema: et_classification
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        default_schema: et_classification
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9001


